apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    control-plane: controller-manager
  name: t2-operator-controller-manager-service
spec:
  ports:
  - name: metrics
    port: 8084
    protocol: TCP
    targetPort: 8084
  - name: health-probe
    port: 8085
    protocol: TCP
    targetPort: 8085
  selector:
    control-plane: controller-manager
status:
  loadBalancer: {}
